### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by kellabyte** [OrangeTide/btree#1]
Any chance this could be updated to support Windows? It doesn't compile using the Visual Studio compiler.

**Comment by OrangeTide** [comment]
I'm not sure what would need to be changed for VS. I don't have that compiler. If you want to paste the errors/warning maybe I can make some suggestions.
(sorry for the late reply, I didn't even know about this feature of github until today!)

**Comment by OrangeTide** [comment]
Closing because no response or pull requests in years.
